[ "$LS_COLORS_CACHE_LOCATION" == "" ] && LS_COLORS_CACHE_LOCATION="/tmp"
[ "$LS_COLORS_CACHE_NAME" == "" ] && LS_COLORS_CACHE_NAME="LS_COLORS_CACHE.sh"
mkdir -p "$LS_COLORS_CACHE_LOCATION"
_LS_COLORS_CACHE_FULL_PATH="$LS_COLORS_CACHE_LOCATION/$LS_COLORS_CACHE_NAME"
if [ ! -O "$_LS_COLORS_CACHE_FULL_PATH" ]; then
  dircolors -b ${0:A:h}/LS_COLORS > "$_LS_COLORS_CACHE_FULL_PATH"
  chmod 400 "$_LS_COLORS_CACHE_FULL_PATH"
fi
source "$_LS_COLORS_CACHE_FULL_PATH"
