LS_COLORS_CACHE_LOCATION="/tmp/LS_COLORS_CACHE.sh"
if [ ! -rO "$LS_COLORS_CACHE_LOCATION" ]; then
  dircolors -b ${0:A:h}/LS_COLORS > "$LS_COLORS_CACHE_LOCATION"
  chmod 400 "$LS_COLORS_CACHE_LOCATION"
fi
source "$LS_COLORS_CACHE_LOCATION"
