#!/usr/bin/env python3
#
"""Check the compiled lscolors.sh file for duplicate extensions."""
import sys
import re
from collections import Counter


def main() -> int:
    with open("../lscolors.sh", "r") as f:
        data = next(f)

    extensions = re.findall(r"\*\.(.*?)=", data)

    if duplicates := [ext for ext, count in Counter(extensions) if count > 1]:
        print(f"Duplicates found: {', '.join(duplicates)}")
        return 1
    else:
        print("No duplicates found.")
        return 0


if __name__ == "__main__":
    sys.exit(main())

# EOF
